"""add nutrition foundation

Revision ID: 3a671dc63f5b
Revises: 3dbdf22b57d2
Create Date: 2026-08-10 14:21:06.884739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a671dc63f5b'
down_revision: Union[str, Sequence[str], None] = '3dbdf22b57d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('calories', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('protein', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('carbs', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fat', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_goals_user_id'), 'nutrition_goals', ['user_id'], unique=True)
    op.add_column('ingredients', sa.Column('calories_per_100g', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('ingredients', sa.Column('protein_per_100g', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('ingredients', sa.Column('carbs_per_100g', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('ingredients', sa.Column('fat_per_100g', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('ingredients', sa.Column('grams_per_piece', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('ingredients', sa.Column('grams_per_ml', sa.Numeric(precision=8, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'grams_per_ml')
    op.drop_column('ingredients', 'grams_per_piece')
    op.drop_column('ingredients', 'fat_per_100g')
    op.drop_column('ingredients', 'carbs_per_100g')
    op.drop_column('ingredients', 'protein_per_100g')
    op.drop_column('ingredients', 'calories_per_100g')
    op.drop_index(op.f('ix_nutrition_goals_user_id'), table_name='nutrition_goals')
    op.drop_table('nutrition_goals')
    # ### end Alembic commands ###
