"""add meal logs

Revision ID: e3ad30e517a8
Revises: fe5faa55ed49
Create Date: 2026-08-11 23:01:26.498316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3ad30e517a8'
down_revision: Union[str, Sequence[str], None] = 'fe5faa55ed49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('meal_name', sa.String(length=160), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('servings', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('calories', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('protein', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('carbs', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_logs_log_date'), 'meal_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_meal_logs_recipe_id'), 'meal_logs', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_meal_logs_user_id'), 'meal_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_logs_user_id'), table_name='meal_logs')
    op.drop_index(op.f('ix_meal_logs_recipe_id'), table_name='meal_logs')
    op.drop_index(op.f('ix_meal_logs_log_date'), table_name='meal_logs')
    op.drop_table('meal_logs')
    # ### end Alembic commands ###
