"""add ingredient aliases

Revision ID: fe5faa55ed49
Revises: 0b80d4fa394f
Create Date: 2026-08-10 21:21:37.423360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe5faa55ed49'
down_revision: Union[str, Sequence[str], None] = '0b80d4fa394f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('alias_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_aliases_alias_name'), 'ingredient_aliases', ['alias_name'], unique=True)
    op.create_index(op.f('ix_ingredient_aliases_ingredient_id'), 'ingredient_aliases', ['ingredient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredient_aliases_ingredient_id'), table_name='ingredient_aliases')
    op.drop_index(op.f('ix_ingredient_aliases_alias_name'), table_name='ingredient_aliases')
    op.drop_table('ingredient_aliases')
    # ### end Alembic commands ###
